### ISSUE TITLE
ea-utils is not found within the provided channels in environment.yaml

### ISSUE THREAD

**Issue by zmorav** [twbattaglia/amplicon-nf#1]
I ran this command:
```
conda env create -f environment.yaml 
```
which gave me this output:
```
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - ea-utils=1.1.2.779
```

Really looking forward to solving this together <3

**Comment by twbattaglia** [comment]
Thank you for pointing this out - it seems it fails due to a lack of a macOS conda package. 

A new version will be eventually pushed that removes this dependency.
